apiVersion: config.istio.io/v1beta1
kind: DestinationPolicy
metadata:
  name: lunar-phase-circuit-breaker
spec:
  destination:
    name: lunar-phase-server
  circuitBreaker:
    simpleCb:
      maxConnections: 1
      httpMaxPendingRequests: 1
      sleepWindow: 3m
      httpDetectionInterval: 1s
      httpMaxEjectionPercent: 100
      httpConsecutiveErrors: 1
      httpMaxRequestsPerConnection: 1
