apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: weather-server-abort
spec:
  destination:
    name: weather-server
  precedence: 10
  route:
  - labels:
      version: "1.0"
  httpFault:
    abort:
      percent: 50
      httpStatus: 400
