apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: lunar-phase-timeout-default
spec:
  destination:
    name: lunar-phase-server
  route:
  - labels:
      serving: "true"
  httpReqTimeout:
    simpleTimeout:
      timeout: 10s
  precedence: 3
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: lunar-phase-timeout-mobile
spec:
  destination:
    name: lunar-phase-server
  route:
  - labels:
      serving: "true"
  httpReqTimeout:
    simpleTimeout:
      timeout: 5s
  precedence: 4
  match:
    request:
      headers:
        user-agent:
          regex: ".*(iPad|Android|iPhone).*"
