apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: forecast-ingress
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:

  - http:
      paths:
      - path: /v2/.*
        backend:
          serviceName: forecast-server
          servicePort: 8080

  - http:
      paths:
      - path: /v1/.*
        backend:
          serviceName: forecast-server-old
          servicePort: 8080
