##################################################################################################
# Forecast service
##################################################################################################
##################################################################################################
# Weather service
##################################################################################################
##################################################################################################
# Lunar phase service
##################################################################################################
##################################################################################################
# Ingress resource (gateway)
##################################################################################################