apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: forecast-server
  labels:
    app: forecast-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: forecast-server
        serving: "true"
    spec:
      containers:
      - name: location-server
        image: sbishyr/forecast-istio:1.0
        imagePullPolicy: Always
        env:
        - name: WEATHER_SERVICE_URL
          value: http://weather-server:8081
        - name: LUNAR_PHASE_SERVICE_URL
          value: http://lunar-phase-server:8082
        ports:
        - containerPort: 8080
          name: http
