apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: location-weather-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:

  - host: locations.istio.com
    http:
      paths:
      - backend:
          serviceName: location-server
          servicePort: 8080

  - host: weather.istio.com
    http:
      paths:
      - backend:
          serviceName: weather-server
          servicePort: 8081
