apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: location-weather-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: location-server
          servicePort: 8080