apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: weather-server-v1
  labels:
    app: weather-server
    version: "1.0"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: weather-server
        version: "1.0"
        serving: "true"
    spec:
      containers:
      - name: weather-server
        image: sbishyr/weather-istio
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: http