apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: icons-delay
spec:
  destination:
    name: icons-server
  precedence: 2
  route:
  - labels:
      serving: "true"
  httpFault:
    delay:
      fixedDelay: 7.000s
      percent: 100
