apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: weather-v2
spec:
  destination:
    name: weather-server
  precedence: 2
  match:
    request:
      headers:
        user-agent:
          regex: ".*Chrome.*"
  route:
  - labels:
      version: "2.0"
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: lunar-phase-v2
spec:
  destination:
    name: lunar-phase-server
  precedence: 2
  match:
    request:
      headers:
        user-agent:
          regex: ".*Chrome.*"
  route:
  - labels:
      version: "2.0"